name: test

on: [push, pull_request]

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go_version: ["1.20", "1.21", "1.22"]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go ${{ matrix.go_version }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go_version }}

    - name: Test
      run: go test -v ./...
